version: '2'
services:
    back:
        build:
            context: ./back/
        command: npm start
        volumes:
            - ./back/:/usr/back
        ports:
            - "8080:8080"
        env_file: ./.env
